#!/bin/sh -e

export PREFIX=""
if [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi

set -x

${PREFIX}autoflake --in-place --recursive doge
${PREFIX}black doge
${PREFIX}isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --combine-as --line-width 88 --recursive --apply doge
# ${PREFIX}mypy apps --ignore-missing-imports --disallow-untyped-defs
